#!/bin/bash

version=${NGINX_VERSION:-1.4.2}
binaries=${OPENSHIFT_REPO_DIR}/versions/$version

pushd tmp

${OPENSHIFT_REPO_DIR}/bin/compile ${OPENSHIFT_REPO_DIR}/tmp

cp -f build/sbin/nginx $binaries/bin/nginx
cp -r build/conf $binaries/conf

popd
rm -rf ${OPENSHIFT_REPO_DIR}/tmp