#!/bin/bash

set +e
mkdir -p tmp/build
set -e

version=${NGINX_VERSION:-1.4.2}
binaries="versions/$version"


bin/compile ./tmp/build

mkdir -p $binaries/bin
cp -f tmp/build/out/nginx $binaries/bin

rm -rf tmp/build